<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Site.master" Title="" CodeFile="AddPartsToRFQ.aspx.cs" Inherits="Mgr_AddPartsToRFQ" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="Server">
    <ul class="breadcrumb">
        <li><a href="SelectProject.aspx">Home</a></li>
        <li><a href="ProjectMenu.aspx">Project</a></li>
        <li><a href="RFQList.aspx">RFQ List</a></li>
        <li class="active">Create RFQ</li>
    </ul>
    <div id="SelectProjectTitle" runat="server" class="ContentHead">
        <h1>Add Line Items</h1>

        <p><b>Project: </b>
            <asp:Label runat="server" ID="ProjectName" />
        </p>
        <p><b>Contract Number: </b>
            <asp:Label runat="server" ID="ContractNumber" /></p>
    </div>

    <asp:DetailsView runat="server" ID="RFQDetails" DataKeyNames="RFQID" SelectMethod="RFQDetails_GetItem" InsertMethod="RFQDetails_InsertItem" UpdateMethod="RFQDetails_UpdateItem"
        EnableViewState="false" AutoGenerateRows="false" ItemType="MaterialManager.Models.RequestForQuote" CssClass="table table-striped table-bordered table-hover" CellPadding="4" AutoGenerateEditButton="true">
        <Fields>
            <asp:BoundField DataField="RFQID" HeaderText="RFQ ID" ReadOnly="true" ><HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle></asp:BoundField>
            <asp:BoundField DataField="JBReferenceCode" HeaderText="RFQ Reference Number" ReadOnly="true" ><HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle></asp:BoundField>
            <asp:BoundField DataField="RFQDate" HeaderText="RFQ Date" ><HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle></asp:BoundField>
            <asp:BoundField DataField="RFQtoVendorDate" HeaderText="RFQ Sent to Vendor"><HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle></asp:BoundField>
            <asp:BoundField DataField="ReviewStatus" HeaderText="Review Status" ReadOnly="true" ><HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle></asp:BoundField>
            <asp:BoundField DataField="ApprovalStatus" HeaderText="Approval Status" ReadOnly="true" ><HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle></asp:BoundField>
        </Fields>    
    </asp:DetailsView>

    <h3>RFQ Line Items</h3>
    <asp:Panel runat="server" id="filterRFQLineItemForm" CssClass="form-group" DefaultButton="FilterRFQLineItemListSubmit">
        <asp:TextBox runat="server" CssClass="form-control col-lg-4" ID="FilterLineItemsTB"></asp:TextBox>
        <asp:DropDownList runat="server" CssClass="form-control col-lg-4" ID="FilterLineItemsDDL">
            <asp:ListItem>JobBoss ID</asp:ListItem>
            <asp:ListItem>NSN</asp:ListItem>
            <asp:ListItem>Part Number</asp:ListItem>
            <asp:ListItem>Description</asp:ListItem>
            <asp:ListItem>Quantity</asp:ListItem>
        </asp:DropDownList>
        <asp:Button runat="server" onClick="FilterRFQLineItemList" CssClass="btn btn-default" ID="FilterRFQLineItemListSubmit" Text="Filter" />
    </asp:Panel>
    <asp:GridView ID="RFQLineItemList" runat="server" AllowSorting="true" AutoGenerateColumns="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.ExtendedLineItem"
        SelectMethod="RFQLineItemList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="RFQLineItemList_RowCommand" OnRowUpdating="RFQLineItemList_RowUpdating"
        AutoGenerateDeleteButton="true" DeleteMethod="RFQLineItemList_DeleteItem" AutoGenerateEditButton="true" UpdateMethod="RFQLineItemList_UpdateItem" DataKeyNames="RFQLineItemID">
        <Columns>
            <asp:TemplateField HeaderText="RFQ ID" SortExpression="RFQID">
                <EditItemTemplate>
                    <asp:Label runat="server" Text='<%# Eval("RFQID") %>' ID="RFQIDLabel"></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("RFQID") %>' ID="RFQIDLabel"></asp:Label>
                </ItemTemplate>

                <HeaderStyle CssClass="hidden"></HeaderStyle>

                <ItemStyle CssClass="hidden"></ItemStyle>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="RFQ Line Item ID" SortExpression="RFQLineItemID">
                <EditItemTemplate>
                    <asp:Label runat="server" Text='<%# Eval("RFQLineItemID") %>' ID="RFQLineItemIDLabel"></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("RFQLineItemID") %>' ID="RFQLineItemIDLabel"></asp:Label>
                </ItemTemplate>

                <HeaderStyle CssClass="hidden"></HeaderStyle>

                <ItemStyle CssClass="hidden"></ItemStyle>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="JobBoss ID" SortExpression="JBMaterialID">
                <EditItemTemplate>
                    <asp:Label runat="server" Text='<%# Eval("JBMaterialID") %>' ID="JBIDLabel"></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("JBMaterialID") %>' ID="JBIDLabel"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Part ID" SortExpression="PartID" HeaderStyle-CssClass="hidden" ItemStyle-CssClass="hidden">
                <EditItemTemplate>
                    <asp:Label runat="server" Text='<%# Eval("PartID") %>' ID="PartIDLabel"></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("PartID") %>' ID="PartIDLabel"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="NSN" SortExpression="NSN">
                <EditItemTemplate>
                    <asp:TextBox runat="server" Text='<%# Bind("NSN") %>' ID="NSNTB"></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("NSN") %>' ID="NSNLabel"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Part Number" SortExpression="PartNumber">
                <EditItemTemplate>
                    <asp:TextBox runat="server" Text='<%# Bind("PartNumber") %>' ID="PartNumberTB"></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("PartNumber") %>' ID="PartNumberLabel"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Description" SortExpression="Description">
                <EditItemTemplate>
                    <asp:TextBox runat="server" Text='<%# Bind("Description") %>' ID="DescriptionTB"></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("Description") %>' ID="DescriptionLabel"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Quantity" SortExpression="Quantity">
                <EditItemTemplate>
                    <asp:TextBox runat="server" Text='<%# Bind("Quantity") %>' ID="QuantityTB" TextMode="Number"></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label runat="server" Text='<%# Bind("Quantity") %>' ID="QuantityLabel"></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField>
                <ItemTemplate>
                    <asp:LinkButton Text="View Job Boss Data" runat="server" CausesValidation="false" CommandName="ViewJobBossData" CommandArgument='<%# Eval("PartID") %>' ControlStyle-CssClass="btn btn-primary">
                    </asp:LinkButton>
                </ItemTemplate>
            </asp:TemplateField>

        </Columns>
    </asp:GridView>

    <!-- Modal Trigger -->
    <button id="CustomPartModalTrigger" class="btn btn-default" data-toggle="modal" data-target="#CustomPartModal">Add Custom Part</button>

    <button id="addPart" runat="server" onserverclick="AddPart_ServerClick" class="btn btn-primary">Add Part</button>
    <button id="AddFromRFQ" runat="server" onserverclick="AddFromRFQ_ServerClick" class="btn btn-primary">Add From RFQ</button>
    <button id="ImportBOMmodalbtn" runat="server" data-toggle="modal" data-target="#ImportBOM" class="btn btn-primary">Import BOM</button>
    <button id="finish" runat="server" onserverclick="Finalize_ServerClick" class="btn btn-primary">Next</button>

    <!-- Modal -->
    <div id="ImportBOM" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add BOM Document</h4>
                </div>
                <div class="modal-body">
                    <fieldset>
                        <div class="form-group">
                            <div class="col-lg-10">
                                <br />
                                <asp:FileUpload ID="BOMFile" runat="server" />
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <asp:Button type="button" ID="AddBOMDocButton" CssClass="btn btn-primary" runat="server" OnClick="AddBOMDocButton_Click" Text="Import"></asp:Button>
                </div>
            </div>

        </div>
    </div>

    <!-- Modal -->
    <div id="CustomPartModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add Custom Part</h4>
                </div>
                <div class="modal-body">
                    <fieldset>
                        <div class="form-group row">
                            <label for="AddJobBossIDTB" class="col-lg-2 control-label">JobBoss ID</label>
                            <div class="col-lg-10">
                                <asp:TextBox runat="server" CssClass="form-control" placeholder="Leave blank if not from JobBoss" ID="AddJobBossIDTB"></asp:TextBox>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="AddNSNTB" class="col-lg-2 control-label">NSN</label>
                            <div class="col-lg-10">
                                <asp:TextBox runat="server" CssClass="form-control" ID="AddNSNTB"></asp:TextBox>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="AddPartNumberTB" class="col-lg-2 control-label">Part Number</label>
                            <div class="col-lg-10">
                                <asp:TextBox runat="server" CssClass="form-control" ID="AddPartNumberTB"></asp:TextBox>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="AddDescriptionTB" class="col-lg-2 control-label">Description</label>
                            <div class="col-lg-10">
                                <asp:TextBox runat="server" CssClass="form-control" ID="AddDescriptionTB"></asp:TextBox>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="AddQuantityTB" class="col-lg-2 control-label">Quantity</label>
                            <div class="col-lg-10">
                                <asp:TextBox runat="server" CssClass="form-control" ID="AddQuantityTB" TextMode="Number"></asp:TextBox>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <asp:Button type="button" ID="AddCustomPartButton" CssClass="btn btn-primary" runat="server" OnClick="AddCustomPartButton_Click" Text="Add"></asp:Button>
                </div>
            </div>

        </div>
    </div>

</asp:Content>
