<%@ Page Title="" Language="C#" MaintainScrollPositionOnPostback="true" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="AddPartsToCatalog.aspx.cs" Inherits="Mgr_AddPartsToCatalog" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="Server">
    <ul class="breadcrumb">
        <li><a href="SelectProject.aspx">Home</a></li>
        <li><a href="ProjectMenu.aspx">Project</a></li>
        <li><a href="PartsCatalog.aspx">Catalog</a></li>
        <li class="active">Add Parts</li>
    </ul>
    <div id="AddToCatalogTitle" runat="server" class="ContentHead">
        <h1>Add New Parts to Catalog</h1>
        <p><b>Project: </b>
            <asp:Label runat="server" ID="ProjectName" />
        </p>
        <p><b>Contract Number: </b>
            <asp:Label runat="server" ID="ContractNumber" /></p>
    </div>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#catalog" data-toggle="tab">Master Catalog Parts</a></li>
        <li><a href="#jobboss" data-toggle="tab">JobBoss Parts</a></li>

    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="catalog">
            <asp:Panel ID="filterCatalogedPartsForm" CssClass="" runat="server" DefaultButton="FilterCatalogedPartsButton">
                <asp:TextBox CssClass="form-control col-lg-4" runat="server" ID="FilterCatalogedPartsTB"></asp:TextBox>
                <asp:DropDownList CssClass="form-control col-lg-4" runat="server" ID="FilterCatalogedPartsDDL">
                    <asp:ListItem>JBMaterialID</asp:ListItem>
                    <asp:ListItem>NSN</asp:ListItem>
                    <asp:ListItem>Part Number</asp:ListItem>
                    <asp:ListItem>Description</asp:ListItem>
                </asp:DropDownList>
                <asp:Button CssClass="btn btn-default" runat="server" ID="FilterCatalogedPartsButton" OnClick="FilterCatalogedPartsList" Text="Filter" />
            </asp:Panel>
            <asp:GridView ID="CatalogedPartsList" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.Part"
                SelectMethod="CatalogedPartsList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="CatalogedPartsList_RowCommand"
                AutoGenerateDeleteButton="false" DataKeyNames="PartID">
                <Columns>
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:Button runat="server" Text="Add To Catalog" CommandName="AddToCatalog" CommandArgument='<%# Eval("PartID") %>' CssClass="btn btn-primary" />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="JBMaterialID" HeaderText="JobBoss ID" SortExpression="JBMaterialID" />
                    <asp:BoundField DataField="PartID" HeaderText="part ID" SortExpression="PartID" HeaderStyle-CssClass="hidden" ItemStyle-CssClass="hidden" />
                    <asp:BoundField DataField="NSN" HeaderText="NSN" SortExpression="NSN" />
                    <asp:BoundField DataField="PartNumber" HeaderText="Part Number" SortExpression="PartNumber" />
                    <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                    <asp:TemplateField>
                        <ItemTemplate>
                            <asp:Button runat="server" Text="View JobBoss Data" CommandName="ViewJobBossData" CommandArgument='<%# Eval("PartID") %>' CssClass="btn btn-primary" />
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:ButtonField Text="View JobBoss Data" CommandName="ViewJobBossData" ControlStyle-CssClass="btn btn-primary" />

                </Columns>
            </asp:GridView>

        </div>
        <div class="tab-pane fade" id="jobboss">
            <asp:Panel ID="filterJobBossPartsForm" CssClass="" runat="server" DefaultButton="FilterJobBossPartsButton">
                <asp:TextBox CssClass="form-control col-lg-4" runat="server" ID="FilterJobBossPartsTB"></asp:TextBox>
                <asp:DropDownList CssClass="form-control col-lg-4" runat="server" ID="FilterJobBossPartsDDL">
                    <asp:ListItem>Material</asp:ListItem>
                    <asp:ListItem>Description</asp:ListItem>
                    <asp:ListItem>Vendor Reference</asp:ListItem>
                    <asp:ListItem>Notes</asp:ListItem>
                    <asp:ListItem>Extended Description</asp:ListItem>
                    <asp:ListItem>Last Updated</asp:ListItem>
                    <asp:ListItem>Primary Vendor</asp:ListItem>
                    <asp:ListItem>Shape</asp:ListItem>
                </asp:DropDownList>
                <asp:Button CssClass="btn btn-default" runat="server" ID="FilterJobBossPartsButton" OnClick="FilterJobBossPartsList" Text="Filter" />
            </asp:Panel>
            <asp:GridView ID="JobBossPartsList" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="JBXML.Respond.JBXMLJBXMLRespondMaterialListQueryRsMaterial"
                SelectMethod="JobBossPartsList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="JobBossPartsList_RowCommand"
                AutoGenerateDeleteButton="false" DataKeyNames="Material">
                <Columns>

                    <asp:ButtonField Text="Add To Catalog" CommandName="AddToCatalog" ControlStyle-CssClass="btn btn-primary" />
                    <asp:BoundField DataField="Material" HeaderText="Material" SortExpression="Material" />
                    <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                    <asp:BoundField DataField="Vendor_Reference" HeaderText="Vendor Reference" SortExpression="Vendor_Reference" />
                    <asp:BoundField DataField="Note_Text" HeaderText="Notes" SortExpression="Note_Text" />
                    <asp:BoundField DataField="Ext_Description" HeaderText="Extended Description" SortExpression="Ext_Description" />
                    <asp:BoundField DataField="Last_Updated" HeaderText="Last Updated" SortExpression="Last_Updated" />
                    <asp:BoundField DataField="Primary_Vendor" HeaderText="Primary Vendor" SortExpression="Primary_Vendor" />
                    <asp:BoundField DataField="Shape" HeaderText="Shape" SortExpression="Shape" />


                </Columns>
            </asp:GridView>
        </div>
    </div>

</asp:Content>

