<%@ Page Title="" MasterPageFile="~/Site.master" Language="C#" AutoEventWireup="true" CodeFile="CreatePO.aspx.cs" Inherits="Mgr_CreatePO" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="Server">
    <ul class="breadcrumb">
        <li><a href="SelectProject.aspx">Home</a></li>
        <li><a href="ProjectMenu.aspx">Project</a></li>
        <li><a href="POList.aspx">PO List</a></li>
        <li class="active">Create PO</li>
    </ul>
    <div id="SelectProjectTitle" runat="server" class="ContentHead">
        <h1>Create New Purchase Order</h1>
        <p>
            <b>Project: </b>
            <asp:Label runat="server" ID="ProjectName" />
        </p>
        <p>
            <b>Contract Number: </b>
            <asp:Label runat="server" ID="ContractNumber" />
        </p>
    </div>
    <h2>Select an RFQ</h2>
    <asp:GridView ID="RFQList" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.RequestForQuote"
        SelectMethod="RFQList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="RFQList_RowCommand"
        AutoGenerateDeleteButton="false" DeleteMethod="RFQList_DeleteItem" DataKeyNames="RFQID" AutoGenerateSelectButton="false" SelectedRowStyle-CssClass="warning" OnSelectedIndexChanged="RFQList_SelectedIndexChanged">
        <Columns>

            <asp:TemplateField>
                <ItemTemplate>
                    <asp:LinkButton Text="Select" runat="server" CausesValidation="false" CommandName="selectRFQ" CommandArgument='<%# Eval("RFQID") %>' ControlStyle-CssClass="btn btn-primary">
                    </asp:LinkButton>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="RFQID" HeaderText="part ID" ItemStyle-CssClass="hidden" HeaderStyle-CssClass="hidden" SortExpression="RFQID" />
            <asp:BoundField DataField="JBReferenceCode" HeaderText="JobBoss RFQ Reference" SortExpression="JBReferenceCode" />
            <asp:BoundField DataField="RFQToVendorDate" HeaderText="RFQ Sent to Vendor" SortExpression="RFQToVendorDate" />
            <asp:BoundField DataField="RFQDate" HeaderText="Date of RFQ" SortExpression="RFQDate" />

        </Columns>
    </asp:GridView>
    <button id="noRFQButton" runat="server" onserverclick="noRFQButton_ServerClick" class="btn btn-primary">Skip RFQ</button>

</asp:Content>
