<%@ Page Title="" Language="C#" MaintainScrollPositionOnPostback="true" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="PartsCatalog.aspx.cs" Inherits="Mgr_PartsCatalog" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">
     <ul class="breadcrumb">
        <li><a href="SelectProject.aspx">Home</a></li>
        <li><a href="ProjectMenu.aspx">Project</a></li>
         <li class="active">Parts Catalog</li>
    </ul>
        <div id ="SelectProjectTitle" runAt="server" class="ContentHead">
        <h1>Parts Catalog</h1>
            <p><b>Project: </b><asp:Label runat="server" ID="ProjectName" /> </p>
        <p><b>Contract Number: </b><asp:Label runat="server" ID="ContractNumber" /></p> 
        </div>
    <asp:Panel id="filter" CssClass="form-group" runat="server" DefaultButton="FilterButton">
        <asp:TextBox CssClass="form-control col-lg-4" runat="server" ID="FilterTB"></asp:TextBox>
        <asp:DropDownList CssClass="form-control col-lg-4" runat="server" ID="FilterDDL">
            <asp:ListItem>JBMaterialID</asp:ListItem>
            <asp:ListItem>NSN</asp:ListItem>
            <asp:ListItem>Part Number</asp:ListItem>
            <asp:ListItem>Description</asp:ListItem>
        </asp:DropDownList>
        <asp:Button CssClass="btn btn-default" runat="server" ID="FilterButton" OnClick="FilterPartsCatalogList" Text="Filter" />
    </asp:Panel>
    <asp:GridView ID="PartsCatalogList" runat="server" AllowSorting="true" AutoGenerateColumns="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.Part"
        SelectMethod="PartsCatalogList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="PartsCatalogList_RowCommand"
        AutoGenerateDeleteButton="true" DeleteMethod="PartsCatalogList_DeleteItem" DataKeyNames="PartID" AutoGenerateEditButton="true" UpdateMethod="PartsCatalogList_UpdateItem">
        <Columns>
            <asp:BoundField DataField="JBMaterialID" ReadOnly="true" HeaderText="JobBoss ID" SortExpression="JBMaterialID" />
            <asp:BoundField DataField="PartID" ReadOnly="true" HeaderText="part ID" SortExpression="PartID" HeaderStyle-CssClass="hidden" ItemStyle-CssClass="hidden" />
            <asp:BoundField DataField="NSN" HeaderText="NSN" SortExpression="NSN" />
            <asp:BoundField DataField="PartNumber" HeaderText="Part Number" SortExpression="PartNumber" />
            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            <asp:TemplateField ShowHeader="False">
                <ItemTemplate>
                    <asp:LinkButton runat="server" Text="Add to Cart" CommandName="AddToCart" CommandArgument='<%# Eval("PartID") %>' CausesValidation="false" ID="LinkButton1"></asp:LinkButton>
                </ItemTemplate>

                <ControlStyle CssClass="btn btn-primary"></ControlStyle>
            </asp:TemplateField>
            <asp:TemplateField ShowHeader="False">
                <ItemTemplate>
                    <asp:LinkButton runat="server" Text="View JobBoss Data" CommandName="ViewJobBossData" CommandArgument='<%# Eval("PartID") %>' CausesValidation="false" ID="LinkButton2"></asp:LinkButton>
                </ItemTemplate>

                <ControlStyle CssClass="btn btn-primary"></ControlStyle>
            </asp:TemplateField>

        </Columns>
    </asp:GridView>
    <p><b><a href="AddPartsToCatalog.aspx">Add New Parts to Catalog</a></b></p>
</asp:Content>

