<%@ Page Title="" Language="C#" MaintainScrollPositionOnPostback="true" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="POList.aspx.cs" Inherits="Mgr_POList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="Server">
    <ul class="breadcrumb">
        <li><a href="SelectProject.aspx">Home</a></li>
        <li><a href="ProjectMenu.aspx">Project</a></li>
        <li class="active">PO List</li>
    </ul>
    <div id="SelectProjectTitle" runat="server" class="ContentHead">
        <h1>Purchase Order List</h1>
        <p><b>Project: </b>
            <asp:Label runat="server" ID="ProjectName" />
        </p>
        <p><b>Contract Number: </b>
            <asp:Label runat="server" ID="ContractNumber" /></p>
    </div>
    <div id="filter" class="form-group">
        <asp:TextBox runat="server" CssClass="form-control col-lg-4" ID="FilterTB"></asp:TextBox>
        <asp:DropDownList runat="server" CssClass="form-control col-lg-4" ID="FilterDDL">
            <asp:ListItem>PO ID</asp:ListItem>
            <asp:ListItem>Vendor</asp:ListItem>
            <asp:ListItem>PO Sent to Vendor</asp:ListItem>
            <asp:ListItem>Required Delivery Date</asp:ListItem>
            <asp:ListItem>Justification</asp:ListItem>
            <asp:ListItem>Review Status</asp:ListItem>
            <asp:ListItem>Approval Status</asp:ListItem>
        </asp:DropDownList>
        <button runat="server" id="FilterSubmit" class="btn btn-default" onserverclick="FilterPOList">Filter</button>
    </div>
    <asp:GridView ID="POList" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.PurchaseOrder"
        SelectMethod="POList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="POList_RowCommand"
        AutoGenerateDeleteButton="true" DeleteMethod="POList_DeleteItem" DataKeyNames="PurchaseOrderID" AutoGenerateSelectButton="false" SelectedRowStyle-CssClass="warning"
        OnSelectedIndexChanged="POList_SelectedIndexChanged" OnRowDataBound="POList_RowDataBound">
        <Columns>

            <asp:HyperLinkField Text="View" DataNavigateUrlFields="PurchaseOrderID" DataNavigateUrlFormatString="POView.aspx?POID={0}" />
            <asp:BoundField DataField="PurchaseOrderID" HeaderText="PO ID" SortExpression="PurchaseOrderID" />
            <asp:BoundField DataField="POVendor" HeaderText="Vendor" SortExpression="POVendor" />
            <asp:BoundField DataField="POtoVendorDate" HeaderText="PO Sent to Vendor" SortExpression="POtoVendorDate" />
            <asp:BoundField DataField="RequiredDeliveryDate" HeaderText="Required Delivery Date" SortExpression="RequiredDeliveryDate" />
            <asp:BoundField DataField="Justification" HeaderText="Justification" SortExpression="Justification" />
            <asp:BoundField DataField="ReviewStatus" HeaderText="Review Status" SortExpression="ReviewStatus" />
            <asp:BoundField DataField="ApprovalStatus" HeaderText="Approval Status" SortExpression="ApprovalStatus" />

        </Columns>
    </asp:GridView>
</asp:Content>

