<%@ Page Title="" Language="C#" MaintainScrollPositionOnPostback="true" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="ProjectKitList.aspx.cs" Inherits="Mgr_ProjectKitList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="Server">

    <ul class="breadcrumb">
        <li><a href="SelectProject.aspx">Home</a></li>
        <li><a href="ProjectMenu.aspx">Project</a></li>
        <li class="active">Kit List</li>
    </ul>
    <div id="SelectProjectTitle" runat="server" class="ContentHead">
        <h1>Kit List</h1>
        <p><b>Project: </b>
            <asp:Label runat="server" ID="ProjectName" />
        </p>
        <p><b>Contract Number: </b>
            <asp:Label runat="server" ID="ContractNumber" /></p>
    </div>
    <asp:Panel ID="filter" CssClass="form-group" runat="server" DefaultButton="FilterButton">
        <asp:TextBox CssClass="form-control col-lg-4" runat="server" ID="FilterTB"></asp:TextBox>
        <asp:DropDownList CssClass="form-control col-lg-4" runat="server" ID="FilterDDL">
            <asp:ListItem>Kit ID</asp:ListItem>
            <asp:ListItem>Description</asp:ListItem>
        </asp:DropDownList>
        <asp:Button CssClass="btn btn-default" runat="server" ID="FilterButton" OnClick="FilterKitList" Text="Filter" />
    </asp:Panel>
    <asp:GridView ID="KitList" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.ProjectKit"
        SelectMethod="KitList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="KitList_RowCommand" OnRowDataBound="KitList_RowDataBound"
        AutoGenerateDeleteButton="true" DeleteMethod="KitList_DeleteItem" DataKeyNames="ProjectKitID" AutoGenerateSelectButton="false" SelectedRowStyle-CssClass="warning" OnSelectedIndexChanged="KitList_SelectedIndexChanged">
        <Columns>

            <asp:HyperLinkField Text="View" DataNavigateUrlFields="ProjectKitID" DataNavigateUrlFormatString="ProjectKitView.aspx?ProjectKitID={0}" />
            <asp:BoundField DataField="ProjectKitID" HeaderText="Kit ID" SortExpression="ProjectKitID" />
            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />

        </Columns>
    </asp:GridView>

</asp:Content>

