<%@ Page Title="" Language="C#" MaintainScrollPositionOnPostback="true" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="ProjectKitView.aspx.cs" Inherits="Mgr_ProjectKitView" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">

    <ul class="breadcrumb">
        <li><a href="SelectProject.aspx">Home</a></li>
        <li><a href="ProjectMenu.aspx">Project</a></li>
        <li><a href="ProjectKitList.aspx">Kit List</a></li>
         <li class="active">Kit</li>
    </ul>
        <div id ="SelectProjectTitle" runAt="server" class="ContentHead">
        <h1>Kit</h1>
            <p><b>Project: </b><asp:Label runat="server" ID="ProjectName" /> </p>
        <p><b>Contract Number: </b><asp:Label runat="server" ID="ContractNumber" /></p> 
        </div>
    <h2>Kit Line Items</h2>
   <asp:Panel id="filter" CssClass="form-group" runat="server" DefaultButton="FilterButton">
        <asp:TextBox CssClass="form-control col-lg-4" runat="server" ID="FilterTB"></asp:TextBox>
        <asp:DropDownList CssClass="form-control col-lg-4" runat="server" ID="FilterDDL">
            <asp:ListItem>JBMaterialID</asp:ListItem>
            <asp:ListItem>NSN</asp:ListItem>
            <asp:ListItem>Description</asp:ListItem>
            <asp:ListItem>Quantity</asp:ListItem>
        </asp:DropDownList>
        <asp:Button CssClass="btn btn-default" runat="server" ID="FilterButton" OnClick="FilterKitItemList" Text="Filter" />
    </asp:Panel>
    <asp:GridView ID="KitItemList" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.ExtendedProjectKitItem"
        SelectMethod="KitItemList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="KitItemList_RowCommand" OnRowDataBound="KitItemList_RowDataBound"
        AutoGenerateDeleteButton="true" DeleteMethod="ProjectKitItemList_DeleteItem" DataKeyNames="ProjectKitItemID" AutoGenerateSelectButton="false" >
        <Columns>
          
            <asp:BoundField DataField="ProjectKitID" HeaderText="Kit ID" ItemStyle-CssClass="hidden" HeaderStyle-CssClass="hidden" SortExpression="ProjectKitID"/>
            <asp:BoundField DataField="JBMaterialID" HeaderText="JBMaterialID" SortExpression="JBMaterialID" />
            <asp:BoundField DataField="PartID" HeaderText="Part ID" SortExpression="PartID" ItemStyle-CssClass="hidden" HeaderStyle-CssClass="hidden" />
            <asp:BoundField DataField="NSN" HeaderText="NSN" SortExpression="NSN"/>
            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
            <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" />
            <asp:TemplateField>
                <ItemTemplate>
                    <asp:LinkButton text="View Job Boss Data" runat="server" CausesValidation="false" CommandName="ViewJobBossData" CommandArgument='<%# Eval("PartID") %>' ControlStyle-CssClass="btn btn-primary">
                    </asp:LinkButton>
                </ItemTemplate>
            </asp:TemplateField>
           
        </Columns>
    </asp:GridView>

    <asp:LinkButton ID="EditLinkButton" CssClass="btn btn-default" runat="server" OnLoad="EditLinkButton_Load" OnClick="EditLinkButton_Click" Text="Edit" />
    <!-- Modal Trigger Button -->
    <button id="CreateRFQButton" class="btn btn-primary" runat="server" onload="CreateRFQButton_Load" data-toggle="modal" data-target="#CreateRFQModal">Create RFQ</button>

    <!-- Modal -->
    <div id="CreateRFQModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Create RFQ</h4>
                </div>
                <div class="modal-body">
                    <fieldset>
                        <div class="form-group row">
                            <label for="RFQDateTime" class="col-lg-2 control-label">RFQ Date</label>
                            <div class="col-lg-10">
                                <asp:TextBox runat="server" CssClass="form-control" TextMode="DateTimeLocal" ID="RFQDateTime"></asp:TextBox>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div runat="server" id="rfqDtValidate" class="font-size-14px"></div>
                        </div>
                        <div class="form-group row">
                            <label for="RFQVendorDateTime" class="col-lg-2 control-label">RFQ Vendor Date</label>
                            <div class="col-lg-10">
                                <asp:TextBox runat="server" CssClass="form-control" TextMode="DateTimeLocal" ID="VendorDateTime"></asp:TextBox>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div runat="server" id="vendorDtValidate" class="font-size-14px"></div>
                        </div>
                    </fieldset>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <asp:Button type="button" ID="CreateRFQSubmitButton" CssClass="btn btn-primary" runat="server" OnClick="CreateRFQSubmitButton_Click" Text="Save"></asp:Button>
                </div>
            </div>

        </div>
    </div>
</asp:Content>

