<%@ Page Title="" Language="C#" MaintainScrollPositionOnPostback="true" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="RFQList.aspx.cs" Inherits="Mgr_RFQList" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="Server">

    <ul class="breadcrumb">
        <li><a href="SelectProject.aspx">Home</a></li>
        <li><a href="ProjectMenu.aspx">Project</a></li>
        <li class="active">RFQ List</li>
    </ul>
    <div id="SelectProjectTitle" runat="server" class="ContentHead">
        <h1>RFQ List</h1>
        <p><b>Project: </b>
            <asp:Label runat="server" ID="ProjectName" />
        </p>
        <p><b>Contract Number: </b>
            <asp:Label runat="server" ID="ContractNumber" /></p>
    </div>
    <div id="filter" class="form-group">
        <asp:TextBox runat="server" CssClass="form-control col-lg-4" ID="FilterTB"></asp:TextBox>
        <asp:DropDownList runat="server" CssClass="form-control col-lg-4" ID="FilterDDL">
            <asp:ListItem>RFQ ID</asp:ListItem>
            <asp:ListItem>JobBoss RFQ Reference</asp:ListItem>
            <asp:ListItem>RFQ Sent to Vendor</asp:ListItem>
            <asp:ListItem>Date of RFQ</asp:ListItem>
            <asp:ListItem>Review Status</asp:ListItem>
            <asp:ListItem>Approval Status</asp:ListItem>
        </asp:DropDownList>
        <button runat="server" id="FilterSubmit" class="btn btn-default" onserverclick="FilterRFQList">Filter</button>
    </div>
    <asp:GridView ID="RFQList" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.RequestForQuote"
        SelectMethod="RFQList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="RFQList_RowCommand" OnRowDataBound="RFQList_RowDataBound"
        AutoGenerateDeleteButton="true" DeleteMethod="RFQList_DeleteItem" DataKeyNames="RFQID" AutoGenerateSelectButton="false" SelectedRowStyle-CssClass="warning" OnSelectedIndexChanged="RFQList_SelectedIndexChanged">
        <Columns>

            <asp:HyperLinkField Text="View" DataNavigateUrlFields="RFQID" DataNavigateUrlFormatString="RFQView.aspx?RFQID={0}" />
            <asp:BoundField DataField="RFQID" HeaderText="part ID" ItemStyle-CssClass="hidden" HeaderStyle-CssClass="hidden" SortExpression="RFQID" />
            <asp:BoundField DataField="JBReferenceCode" HeaderText="JobBoss RFQ Reference" SortExpression="RFQID" />
            <asp:BoundField DataField="RFQToVendorDate" HeaderText="RFQ Sent to Vendor" SortExpression="RFQToVendorDate" />
            <asp:BoundField DataField="RFQDate" HeaderText="Date of RFQ" SortExpression="RFQDate" />
            <asp:BoundField DataField="ReviewStatus" HeaderText="Review Status" SortExpression="ReviewStatus" />
            <asp:BoundField DataField="ApprovalStatus" HeaderText="Approval Status" SortExpression="ApprovalStatus" />

        </Columns>
    </asp:GridView>

</asp:Content>

