<%@ Page Title="" Language="C#" MaintainScrollPositionOnPostback="true" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="RFQView.aspx.cs" Inherits="Mgr_RFQView" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="Server">
    <ul class="breadcrumb">
        <li><a href="SelectProject.aspx">Home</a></li>
        <li><a href="ProjectMenu.aspx">Project</a></li>
        <li><a href="RFQList.aspx">RFQ List</a></li>
        <li class="active">RFQ Details</li>
    </ul>
    <div id="SelectProjectTitle" runat="server" class="ContentHead">
        <h1>RFQ Details</h1>

        <p>
            <b>Project: </b>
            <asp:Label runat="server" ID="ProjectName" />
        </p>
        <p>
            <b>Contract Number: </b>
            <asp:Label runat="server" ID="ContractNumber" />
        </p>
    </div>

    <asp:DetailsView runat="server" ID="RFQDetails" DataKeyNames="RFQID" SelectMethod="RFQDetails_GetItem" InsertMethod="RFQDetails_InsertItem" UpdateMethod="RFQDetails_UpdateItem"
        EnableViewState="false" AutoGenerateRows="false" ItemType="MaterialManager.Models.RequestForQuote" CssClass="table table-striped table-bordered table-hover" CellPadding="4">
        <Fields>
            <asp:BoundField DataField="RFQID" HeaderText="RFQ ID">
                <HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle>
            </asp:BoundField>
            <asp:BoundField DataField="JBReferenceCode" HeaderText="RFQ Reference Number">
                <HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle>
            </asp:BoundField>
            <asp:BoundField DataField="RFQDate" HeaderText="RFQ Date">
                <HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle>
            </asp:BoundField>
            <asp:BoundField DataField="RFQtoVendorDate" HeaderText="RFQ Sent to Vendor">
                <HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle>
            </asp:BoundField>
            <asp:BoundField DataField="ReviewStatus" HeaderText="Review Status">
                <HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle>
            </asp:BoundField>
            <asp:BoundField DataField="ApprovalStatus" HeaderText="Approval Status">
                <HeaderStyle CssClass="info" Font-Bold="True" Width="25%"></HeaderStyle>
            </asp:BoundField>
        </Fields>
    </asp:DetailsView>

    <asp:LinkButton ID="EditLinkButton" CssClass="btn btn-default" runat="server" OnLoad="EditLinkButton_Load" OnClick="EditLinkButton_Click" Text="Edit" />
    <asp:Button ID="RevertStatus" runat="server" OnClick="RevertStatus_Clicked" OnLoad="RevertStatus_OnLoad" ControlStyle-CssClass="btn btn-default" />
    <asp:Button ID="ChangeStatus" runat="server" OnClick="ChangeStatus_Clicked" OnLoad="ChangeStatus_OnLoad" ControlStyle-CssClass="btn btn-primary" />

    <!-- Export To Excel Section -->
    <button runat="server" class="btn btn-info pull-right" data-toggle="modal" data-target="#ExportModal">Export RFQ</button>

    <div class="jumbotron">
        <h3>RFQ Line Items</h3>
        <asp:Panel runat="server" ID="filterRFQLineItemForm" CssClass="form-group" DefaultButton="FilterRFQLineItemListSubmit">
            <asp:TextBox runat="server" CssClass="form-control col-lg-4" ID="FilterLineItemsTB"></asp:TextBox>
            <asp:DropDownList runat="server" CssClass="form-control col-lg-4" ID="FilterLineItemsDDL">
                <asp:ListItem>JobBoss ID</asp:ListItem>
                <asp:ListItem>NSN</asp:ListItem>
                <asp:ListItem>Part Number</asp:ListItem>
                <asp:ListItem>Description</asp:ListItem>
                <asp:ListItem>Quantity</asp:ListItem>
            </asp:DropDownList>
            <asp:Button runat="server" OnClick="FilterRFQLineItemList" CssClass="btn btn-default" ID="FilterRFQLineItemListSubmit" Text="Filter" />
        </asp:Panel>
        <asp:GridView ID="RFQLineItemList" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.ExtendedLineItem"
            SelectMethod="RFQLineItemList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="RFQLineItemList_RowCommand" OnRowDataBound="RFQLineItemList_RowDataBound"
            AutoGenerateDeleteButton="true" DeleteMethod="RFQLineItemList_DeleteItem" DataKeyNames="RFQLineItemID" AutoGenerateSelectButton="false">
            <Columns>

                <asp:BoundField DataField="RFQID" HeaderText="RFQ ID" ItemStyle-CssClass="hidden" HeaderStyle-CssClass="hidden" SortExpression="RFQID" />
                <asp:BoundField DataField="JBMaterialID" HeaderText="JobBoss ID" SortExpression="JBMaterialID" />
                <asp:BoundField DataField="PartID" HeaderText="Part ID" SortExpression="PartID" HeaderStyle-CssClass="hidden" ItemStyle-CssClass="hidden" />
                <asp:BoundField DataField="NSN" HeaderText="NSN" SortExpression="NSN" />
                <asp:BoundField DataField="PartNumber" HeaderText="Part Number" SortExpression="PartNumber" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" />

                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:LinkButton Text="View Job Boss Data" runat="server" CausesValidation="false" CommandName="ViewJobBossData" CommandArgument='<%# Eval("PartID") %>' ControlStyle-CssClass="btn btn-primary">
                        </asp:LinkButton>
                    </ItemTemplate>
                </asp:TemplateField>

            </Columns>
        </asp:GridView>
    </div>

    <div class="jumbotron">
        <h3>RFQ Documents</h3>
        <asp:Panel runat="server" ID="filterDocs" CssClass="form-group" DefaultButton="FilterDocsSubmit">
            <asp:TextBox runat="server" CssClass="form-control col-lg-4" ID="FilterDocsTB"></asp:TextBox>
            <asp:DropDownList runat="server" CssClass="form-control col-lg-4" ID="FilterDocsDDL">
                <asp:ListItem>File Name</asp:ListItem>
                <asp:ListItem>Description</asp:ListItem>
            </asp:DropDownList>
            <asp:Button runat="server" CssClass="btn btn-default" OnClick="FilterRFQDocumentList" ID="FilterDocsSubmit" Text="Filter" />
        </asp:Panel>
        <asp:GridView ID="RFQDocumentList" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.RFQDocument"
            SelectMethod="RFQDocumentList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="RFQDocumentList_RowCommand" OnRowDataBound="RFQDocumentList_RowDataBound"
            AutoGenerateDeleteButton="true" DeleteMethod="RFQDocumentList_DeleteItem" DataKeyNames="RFQDocID" AutoGenerateSelectButton="false">
            <Columns>

                <asp:BoundField DataField="RFQID" HeaderText="RFQ ID" ItemStyle-CssClass="hidden" HeaderStyle-CssClass="hidden" SortExpression="RFQID" />
                <asp:BoundField DataField="RFQDocID" HeaderText="RFQ Document ID" ItemStyle-CssClass="hidden" HeaderStyle-CssClass="hidden" SortExpression="RFQDocID" />
                <asp:BoundField DataField="FileName" HeaderText="File Name" SortExpression="FileName" />
                <asp:BoundField DataField="Description" HeaderText="File Description" SortExpression="Description" />
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:Button runat="server" Text="Download" CommandName="DownloadFile" CommandArgument='<%# Eval("FileName") + "," + Eval("RFQDocID") %>' CssClass="btn btn-primary" />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>

        <asp:Label runat="server" ID="LabelAddStatus"></asp:Label>
        <!-- Trigger the modal with a button -->
        <button type="button" class="btn btn-info" id="AddDocumentButton" runat="server" onload="AddDocumentButton_Load" data-toggle="modal" data-target="#addDocModal">Add Document</button>
    </div>

    <div class="jumbotron">
        <h3>Quotes Received</h3>
        <asp:Panel runat="server" ID="filterQuotes" CssClass="form-group" DefaultButton="FilterQuotesReceivedButton">
            <asp:TextBox runat="server" CssClass="form-control col-lg-4" ID="FilterQuotesTB"></asp:TextBox>
            <asp:DropDownList runat="server" CssClass="form-control col-lg-4" ID="FilterQuotesDDL">
                <asp:ListItem>RFQ</asp:ListItem>
                <asp:ListItem>RFQ Reference</asp:ListItem>
                <asp:ListItem>Last Updated</asp:ListItem>
                <asp:ListItem>Quoted By</asp:ListItem>
                <asp:ListItem>Submitted Date</asp:ListItem>
                <asp:ListItem>Expired Date</asp:ListItem>
                <asp:ListItem>Comments</asp:ListItem>
                <asp:ListItem>Notes</asp:ListItem>
                <asp:ListItem>Status</asp:ListItem>
                <asp:ListItem>Status Date</asp:ListItem>
            </asp:DropDownList>
            <asp:Button runat="server" CssClass="btn btn-default" OnClick="FilterQuotesReceived" ID="FilterQuotesReceivedButton" Text="Filter" />
        </asp:Panel>
        <asp:GridView ID="QuotesReceived" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="JBXML.Respond.JBXMLJBXMLRespondQuoteListQueryRsQuote"
            SelectMethod="QuotesReceived_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="QuotesReceived_RowCommand"
            DataKeyNames="RFQ" AutoGenerateSelectButton="false">
            <Columns>

                <asp:BoundField DataField="RFQ" HeaderText="RFQ" SortExpression="RFQ" />
                <asp:BoundField DataField="Reference" HeaderText="RFQ Reference" SortExpression="Reference" />
                <asp:BoundField DataField="Last_Updated" HeaderText="Last Updated" SortExpression="Last_Updated" />
                <asp:BoundField DataField="Quoted_By" HeaderText="Quoted By" SortExpression="Quoted_By" />
                <asp:BoundField DataField="Submitted_Date" HeaderText="Submitted Date" SortExpression="Submitted_Date" />
                <asp:BoundField DataField="Expiration_Date" HeaderText="Expired Date" SortExpression="Expiration_Date" />
                <asp:BoundField DataField="Comments" HeaderText="Comments" SortExpression="Comments" />
                <asp:BoundField DataField="Note_Text" HeaderText="Notes" SortExpression="Note_Text" />
                <asp:BoundField DataField="Status" HeaderText="Status" SortExpression="Status" />
                <asp:BoundField DataField="Status_Date" HeaderText="Status Date" SortExpression="Status_Date" />



            </Columns>
        </asp:GridView>
    </div>

    <div class="jumbotron">
        <h3>Purchase Orders</h3>
        <asp:Panel ID="filter" CssClass="form-group" runat="server" DefaultButton="FilterPOSubmit">
            <asp:TextBox runat="server" CssClass="form-control col-lg-4" ID="FilterTB"></asp:TextBox>
            <asp:DropDownList runat="server" CssClass="form-control col-lg-4" ID="FilterDDL">
                <asp:ListItem>PO ID</asp:ListItem>
                <asp:ListItem>PO Sent to Vendor</asp:ListItem>
                <asp:ListItem>Required Delivery Date</asp:ListItem>
                <asp:ListItem>Justification</asp:ListItem>
                <asp:ListItem>Review Status</asp:ListItem>
                <asp:ListItem>Approval Status</asp:ListItem>
            </asp:DropDownList>
            <asp:Button runat="server" CssClass="btn btn-default" ID="FilterPOSubmit" OnClick="FilterPOList" Text="Filter" />
        </asp:Panel>
        <asp:GridView ID="POList" runat="server" AllowSorting="true" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4" ItemType="MaterialManager.Models.PurchaseOrder"
            SelectMethod="POList_GetData" CssClass="table table-striped table-bordered table-hover" OnRowCommand="POList_RowCommand"
            AutoGenerateDeleteButton="false" DeleteMethod="POList_DeleteItem" DataKeyNames="PurchaseOrderID" AutoGenerateSelectButton="false" SelectedRowStyle-CssClass="warning"
            OnSelectedIndexChanged="POList_SelectedIndexChanged">
            <Columns>

                <asp:HyperLinkField Text="View" DataNavigateUrlFields="PurchaseOrderID" DataNavigateUrlFormatString="POView.aspx?POID={0}" />
                <asp:BoundField DataField="PurchaseOrderID" HeaderText="PO ID" SortExpression="PurchaseOrderID" />
                <asp:BoundField DataField="POVendor" HeaderText="Vendor" SortExpression="POVendor" />
                <asp:BoundField DataField="POtoVendorDate" HeaderText="PO Sent to Vendor" SortExpression="POtoVendorDate" />
                <asp:BoundField DataField="RequiredDeliveryDate" HeaderText="Required Delivery Date" SortExpression="RequiredDeliveryDate" />
                <asp:BoundField DataField="Justification" HeaderText="Justification" SortExpression="Justification" />
                <asp:BoundField DataField="ReviewStatus" HeaderText="Review Status" SortExpression="ReviewStatus" />
                <asp:BoundField DataField="ApprovalStatus" HeaderText="Approval Status" SortExpression="ApprovalStatus" />

            </Columns>
        </asp:GridView>
    </div>

    <!-- Modal -->
    <div id="addDocModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add RFQ Document</h4>
                </div>
                <div class="modal-body">
                    <fieldset>


                        <div class="form-group">
                            <label for="fileDescription" class="col-lg-2 control-label">File Description:</label>
                            <div class="col-lg-10">
                                <asp:TextBox runat="server" CssClass="form-control" Rows="3" ID="fileDescription" placeholder="Description of file..."></asp:TextBox>

                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-lg-10">
                                <br />
                                <asp:FileUpload ID="RFQFile" runat="server" />
                            </div>
                        </div>

                    </fieldset>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <asp:Button type="button" ID="AddDocButton" CssClass="btn btn-primary" runat="server" OnClick="AddDocButton_Click" Text="Save"></asp:Button>
                </div>
            </div>

        </div>
    </div>

    <!-- Modal -->
    <div id="ExportModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Export RFQ</h4>
                </div>
                <div class="modal-body">
                    <fieldset>
                        <div class="form-group">
                            <label for="ExportOption" class="col-lg-2 control-label">Excel Format:</label>
                            <div class="col-lg-10">
                                <asp:DropDownList ID="ExportOption" CssClass="form-control" runat="server">
                                    <asp:ListItem Text="Vertical" Value="1"></asp:ListItem>
                                    <asp:ListItem Text="Horizontal" Value="2"></asp:ListItem>
                                </asp:DropDownList>
                            </div>
                        </div>
                        <div class="form-group">
                            <asp:GridView ID="ExportRFQDocumentList" runat="server" AllowSorting="false" AutoGenerateColumns="false" ShowFooter="false" GridLines="Vertical" CellPadding="4"
                                ItemType="MaterialManager.Models.RFQDocument" SelectMethod="RFQDocumentList_GetData" CssClass="table table-striped table-bordered table-hover"
                                OnRowCommand="RFQDocumentList_RowCommand" AutoGenerateDeleteButton="false" DataKeyNames="RFQDocID"
                                AutoGenerateSelectButton="false">
                                <Columns>
                                    <asp:TemplateField>
                                        <ItemTemplate>
                                            <asp:CheckBox runat="server" ID="DownloadCB" Checked="true" />
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:BoundField DataField="RFQID" HeaderText="RFQ ID" ItemStyle-CssClass="hidden" HeaderStyle-CssClass="hidden" SortExpression="RFQID" />
                                    <asp:BoundField DataField="RFQDocID" HeaderText="RFQ Document ID" ItemStyle-CssClass="hidden" HeaderStyle-CssClass="hidden" SortExpression="RFQDocID" />
                                    <asp:BoundField DataField="FileName" HeaderText="File Name" SortExpression="FileName" />
                                    <asp:BoundField DataField="Description" HeaderText="File Description" SortExpression="Description" />
                                </Columns>
                            </asp:GridView>
                        </div>
                    </fieldset>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <asp:Button ID="ExcelExport" runat="server" OnClick="ExcelExport_Click" ControlStyle-CssClass="btn btn-info" Text="Export RFQ" />
                </div>
            </div>

        </div>
    </div>

</asp:Content>

